### ISSUE TITLE
Errors when trying to add vector basemap

### ISSUE THREAD

**Issue by cybersea** [Esri/geodev-hackerlabs#207] opened 2017-06-13 21:20 UTC
Getting errors when trying to add vector basemap when following this exercise

geodev-hackerlabs/design/apply_vector_basemap/lab.md

Error
The layer, World Street Map (Night - WGS84), can not be added to the map because its coordinate system or tiling scheme can't be adjusted to align properly with the basemap.   

Got the same error when trying other vector basemaps

**Comment by andygup** [comment] 2017-06-13 22:48
@cybersea Thanks for the heads-up. We'll need to update this exercise. 

For now adjust your search parameters to `world street map night vector mature`. That map has the correct projection and will work with the exercise. 

The issue is the original map we provide for the exercise uses a different coordinate system from the supplied vector base maps.

**Comment by jgravois** [comment] 2017-06-14 06:09
@andygup why are we directing folks to load 'mature' vector basemaps? it seems like it would be better to have them load the latest and greatest.

**Comment by andygup** [comment] 2017-06-14 14:47
@jgravois As noted that's a temporary suggestion. If you know where the latest and greatest reside then drop a note here for when the lab gets updated in the next few days.

As a general note, I'm also unclear on the meaning behind this statement `(DO NOT CLICK ADD!) > Add to Map`?

**Comment by jgravois** [comment] 2017-06-14 16:25
> If you know where the latest and greatest reside...

down the line, the vector basemaps will be included in the basemap gallery widget, but in the meantime i'd suggest using this as the search term in the lab: `owner:esri type:tile layer`

> I'm also unclear on the meaning behind this statement...

agreed.  totally confusing.

**Closed as completed** 2017-06-14 18:07 UTC
